class Api::V1::SessionsController < ApplicationController
  # skips the 'authenticate_user!'' callback before the 'create' action. When a user is logging in, they do not yet have an authentication token
  # so they cannot be authenticated. Without skipping this callback, the login request would always be rejected, making it impossible for users to sign in.
  skip_before_action :authenticate_user!, only: [ :create ]

  def create
    # finds a user in the database based on the email address provided in the request params[:email]. If no matching user is found
    # user will be nil
    user = User.find_by(email: params[:email])
    # user&.valid_password? - checks whether the user exists (&. safely handles the case where user is nil, preventing a `NoMethodError`)
    if user&.valid_password?(params[:password])
      # Calls the generate_jwt method on the user object. This method generates a JWT containing the user's ID and an expiration timestamp
      token = user.generate_jwt
      # render - is a Rails method that defines what is returned in the HTTP response
      # json: - is an option that tells Rails to return the response in JSON format
      # token – generated by JWT.
      # user – the authenticated user's data (e.g., `id`, `email`, `role`, etc.)
      # status: :ok – returns the HTTP 200 OK status code, indicating a successful request
      render json: { token: token, user: user }, status: :ok
    else
      # status: :unauthorized – returns the HTTP 401 Unauthorized status code
      render json: { error: "Invalid email or password" }, status: :unauthorized
    end
  end
  # logout action

  def destroy
    # head - Rails method that returns an HTTP response without a response body (headers only).
    # :no_content - shorthand for the HTTP 204 No Content status code.
    # The server indicates that the request was successfully processed but does not return any response data.
    head :no_content
  end
end
