class Course < ApplicationRecord
  belongs_to :school
  # This is automaticly generated by Rails when we used this "rails g model Class name:string description:text category:string level:string
  # age_group:string duration:integer price:decimal school:references teacher:references max_students:integer"
  # teacher:references - rails creates a Teacher model with a table of teachers. But we don't have a Teacher model. We store teachers in a
  # User model (with the Teacher role).
  # belongs_to - Rails method that creates a relationship between model, :teacher - name of the association. That's how you will refer to this
  # connection in your code. This allows you to write : course.teacher – and you will get a teacher object.
  # class_name: "User" - option (parameter) for belongs_to. It tells Rails to don't look for a Teacher model. Use a User model instead.

  # belongs_to :teacher
  belongs_to :teacher, class_name: "User"
end
